enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

#[Spotify]
#uptodown-dlurl = "https://spotify.en.uptodown.com/android"
#version = "9.0.44.478"

[Strava]
archive-dlurl = "https://github.com/soudblox/nichdant-revanced/releases/download/5/com.strava_411.10-12392291_2arch_7dpi_11lang_6b9fb1b348d180530286711dec563179_apkmirror.com.apkm"

#[Tiktok]
#apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
#version = "36.5.4"
